#!/usr/bin/env bats
# cairn-board-invariance.bats — the board renders the same bytes it rendered
# before the model underneath it changed.
#
# Under test: the whole stdout render path of cairn-status.sh, compared
# byte for byte against references committed in tests/fixtures/board-render/
# and captured from cairn-status.py BEFORE phase 20 touched it. "The existing
# tests still pass" is not proof that a render is unchanged — they cover what
# they already covered, and a change in the wrong place can pass all of them
# while moving a space, an order or a truncation. This file is the proof:
# the bytes, or nothing.
#
# The references are regenerated by a human running
# `bash tests/fixtures/board-render/regenerate.sh` and READING the diff it
# prints. No test here may ever call it — a test that regenerates its own
# reference before comparing is a rubber stamp.
#
# Assertion style note (same as cairn-status.bats): a failing `[[ ]]` or
# `! cmd` mid-test does NOT fail a bats test on this bash, so every check
# lands on a plain `[ ]` over a run-captured `$status`.

load 'helpers'

STATUS_SH="$CAIRN_REPO_ROOT/cairn/scripts/cairn-status.sh"
BOARD_FIXTURES="$CAIRN_TESTS_DIR/fixtures/board-render"

setup() {
  require_bd
  make_tmp_repo
  make_board_fixture "$PWD"
}

# Render the fixture with the given flags and diff it against the committed
# reference NAME. Prints the diff on failure — an exit code alone says
# "different" and nothing about how.
assert_render_matches() {
  local name="$1"
  shift
  local actual="$BATS_TEST_TMPDIR/render-$name.txt"
  bash "$STATUS_SH" "$@" --color=never > "$actual"
  run diff -u "$BOARD_FIXTURES/$name.txt" "$actual"
  if [ "$status" -ne 0 ]; then
    echo "render drifted from tests/fixtures/board-render/$name.txt" >&2
    printf '%s\n' "$output" >&2
  fi
  [ "$status" -eq 0 ]
}

# ─── The reference renders ───────────────────────────────────────────────────

@test "the wide board renders the reference bytes" {
  assert_render_matches w100 --width 100
}
