#!/usr/bin/env bats
# cairn-init.bats — exercises cairn/scripts/cairn-init.sh against throwaway
# repos: git + bd bootstrap, the .gitignore entries promised by docs/sync.md §4,
# and idempotent re-runs (no duplicate lines).

load 'helpers'

# Every entry cairn-init must gitignore (docs/sync.md §4). The first three are
# the pre-1.4 set; the rest were generated by v1.4 code with no ignore rule.
CAIRN_GITIGNORE_ENTRIES=(
  '.cairn/id-map.json'
  '.cairn/state.json'
  '.cairn/conflicts.json'
  '.cairn/journal.jsonl*'
  '.cairn/journal/*'
  '!.cairn/journal/*.jsonl'
  '.cairn/reconcile-evidence.json'
  '.cairn/hook.log'
  '.cairn/migrate-plan.json'
  '.cairn/migrate-state.json'
  '.cairn/plugin-root'
)

# The pre-1.4 .gitignore, verbatim — the state of anyone upgrading from 1.4.x.
CAIRN_LEGACY_ENTRIES=(
  '.cairn/id-map.json'
  '.cairn/state.json'
  '.cairn/conflicts.json'
)

# Create one file per generated path under .cairn/, in the cwd repo. Includes
# the two siblings cairn-journal.py writes next to the journal (a compaction
# temp file and the compaction lock) — an exact-name ignore would miss both.
make_cairn_generated_files() {
  mkdir -p .cairn
  local f
  for f in id-map.json state.json conflicts.json journal.jsonl \
           journal.jsonl.tmp-abc123 journal.jsonl.compact.lock \
           reconcile-evidence.json hook.log migrate-plan.json \
           migrate-state.json plugin-root; do
    printf 'generated\n' > ".cairn/$f"
  done
}

# Create the two .cairn/ files that are meant to be COMMITTED: the sync backend
# config and the optional context-budget tuning. Both configure the whole team.
make_cairn_committable_files() {
  mkdir -p .cairn
  printf '{"backends":{}}\n' > .cairn/sync.json
  printf '{"budget":{}}\n' > .cairn/context.json
}

# Print every `git status` untracked path under .cairn/, one per line. Uses
# -uall so git lists files individually instead of collapsing a fully-untracked
# .cairn/ into a single `?? .cairn/` line.
cairn_untracked() {
  git status --porcelain -uall | sed -n 's/^?? //p' | grep '^\.cairn/'
}

#-----------------------------------------------------------------------------
# LANG-01 (plan 24-02) — the language question is part of INSTALLATION, and
# these are assertions about the command file, which is the contract: the
# script below wires git and bd, and the asking happens in the prompt.
#
# Why the POSITION is load-bearing and not a preference: step 6 hands off to
# /gsd:new-project, which spawns its own subagents (researcher, synthesizer,
# roadmapper). A question asked after that hand-off is a question asked after
# the project's first subagents already answered in the wrong language, which
# is the defect LANG-01 exists to prevent.
#
# Assertion style here matches tests/cairn-parallel-autonomous.bats: line
# numbers captured by a helper and compared as integers, `grep -cF` under
# `run bash -c` for substrings.
#-----------------------------------------------------------------------------

INIT_COMMAND_FILE="$CAIRN_REPO_ROOT/cairn/commands/init.md"
INIT_DOC_FILE="$CAIRN_REPO_ROOT/cairn/docs/commands/init.md"

# First line number of a fixed string in a file, empty when absent.
init_anchor_line() {
  grep -nF -- "$2" "$1" | head -1 | cut -d: -f1
}

@test "init asks the response language BEFORE the /gsd:new-project hand-off" {
  local l_ask l_handoff
  l_ask="$(init_anchor_line "$INIT_COMMAND_FILE" 'get agents.response_language --json')"
  # The section heading, not the first mention of the command: step 0 names
  # `/gsd:new-project` too, in the sentence that forbids running it over an
  # existing .planning/. Anchoring on the mention would compare against the
  # wrong line and pass for the wrong reason.
  l_handoff="$(init_anchor_line "$INIT_COMMAND_FILE" '## 6. Hand off')"
  [ -n "$l_ask" ]
  [ -n "$l_handoff" ]
  # Breaks if the question migrates after the hand-off — the case where the
  # first subagents of the project have already answered in English.
  [ "$l_ask" -lt "$l_handoff" ]
}

@test "init names English as the default and refuses to ask again when a choice exists" {
  run bash -c "grep -cF -- 'English is the default, and it is pre-selected' '$INIT_COMMAND_FILE'"
  [ "$status" -eq 0 ]
  [ "$output" -ge 1 ]

  # Roadmap success criterion 3: an installed project is not changed without
  # being asked. Breaks on an init that overwrites an existing choice.
  run bash -c "grep -cF -- 'do not ask, and do not write anything' '$INIT_COMMAND_FILE'"
  [ "$status" -eq 0 ]
  [ "$output" -ge 1 ]
  run bash -c "grep -cF -- 'source\` is already \`file\` or \`planning\`' '$INIT_COMMAND_FILE'"
  [ "$status" -eq 0 ]
  [ "$output" -ge 1 ]
}

@test "init writes the language only through cairn-config, never into GSD's config directly" {
  # An assertion on the EXACT count, zero, not on the absence of a phrase:
  # `gsd-tools query config-set response_language` creates .planning/ when it
  # is absent (M-1), and a .planning/ holding only config.json makes step 0's
  # detect answer A instead of D (M-2), which stops the next run of this very
  # command. Breaks the moment somebody "simplifies" by writing GSD's key here.
  run bash -c "grep -cF -- 'config-set response_language' '$INIT_COMMAND_FILE' || true"
  [ "$output" -eq 0 ]

  run bash -c "grep -cF -- 'set agents.response_language' '$INIT_COMMAND_FILE'"
  [ "$status" -eq 0 ]
  # Twice: once at 3.5 where it records the answer, once at step 6 where the
  # propagation actually fires.
  [ "$output" -eq 2 ]
}

@test "init's documentation page carries the same step, in the same place" {
  local l_ask l_handoff
  l_ask="$(init_anchor_line "$INIT_DOC_FILE" 'Step 3.5')"
  l_handoff="$(init_anchor_line "$INIT_DOC_FILE" 'Step 6')"
  [ -n "$l_ask" ]
  [ -n "$l_handoff" ]
  [ "$l_ask" -lt "$l_handoff" ]
  run bash -c "grep -cF -- 'agents.response_language' '$INIT_DOC_FILE'"
  [ "$status" -eq 0 ]
  [ "$output" -ge 1 ]
}

@test "cairn-init bootstraps git + bd and gitignores the .cairn state files" {
  require_bd
  make_tmp_repo

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]

  [ -d .git ]
  [ -d .beads ]
  local entry
  for entry in "${CAIRN_GITIGNORE_ENTRIES[@]}"; do
    grep -qxF "$entry" .gitignore
  done
}

@test "cairn-init re-run is idempotent — no duplicate .gitignore entries" {
  require_bd
  make_tmp_repo

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]
  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]
  grep -qF '.cairn state files already gitignored' <<< "$output"

  local entry
  for entry in "${CAIRN_GITIGNORE_ENTRIES[@]}"; do
    [ "$(grep -cxF "$entry" .gitignore)" -eq 1 ]
  done
}

@test "cairn-init completes a legacy .gitignore that only has the retired .beacon-sent marker" {
  require_bd
  make_tmp_repo
  printf '.cairn/.beacon-sent\n' > .gitignore

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]

  # The legacy entry is left alone (still single); every missing entry is
  # appended once each. cairn-init no longer writes .beacon-sent itself.
  [ "$(grep -cxF '.cairn/.beacon-sent' .gitignore)" -eq 1 ]
  local entry
  for entry in "${CAIRN_GITIGNORE_ENTRIES[@]}"; do
    [ "$(grep -cxF "$entry" .gitignore)" -eq 1 ]
  done
}

@test "after cairn-init no generated .cairn file shows up as untracked" {
  require_bd
  make_tmp_repo
  make_cairn_generated_files

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]

  # Phase 18's symptom: a prepared worktree that stays `?? .cairn/` forever,
  # so cleanup never considers it removable. grep exits 1 on no match, so
  # status 1 IS the passing case; any leftover is echoed for diagnosis.
  run cairn_untracked
  if [ "$status" -eq 0 ]; then
    echo "still untracked under .cairn/:" >&2
    echo "$output" >&2
  fi
  [ "$status" -eq 1 ]
}

@test "cairn-init leaves the committable .cairn config files visible to git" {
  require_bd
  make_tmp_repo
  make_cairn_generated_files
  make_cairn_committable_files

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]

  # sync.json (docs/sync.md §4) and context.json configure the whole team, so
  # git must still see them. This is what forbids the one-line shortcuts —
  # ignoring `.cairn/` wholesale, or a `.cairn/*.json` wildcard — both of which
  # would hide files a team is meant to share.
  run git status --porcelain -uall
  [ "$status" -eq 0 ]
  grep -qF '?? .cairn/sync.json' <<< "$output"
  grep -qF '?? .cairn/context.json' <<< "$output"
}

@test "cairn-init upgrades a pre-1.4 .gitignore without duplicating its entries" {
  require_bd
  make_tmp_repo
  printf '%s\n' "${CAIRN_LEGACY_ENTRIES[@]}" > .gitignore

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]

  # REL-04's actual scenario: this is what "re-run /cairn:init" has to do on
  # the machine of someone who installed before v1.4. Every entry ends up
  # present exactly once — the ones that were already there included.
  local entry
  for entry in "${CAIRN_GITIGNORE_ENTRIES[@]}"; do
    [ "$(grep -cxF "$entry" .gitignore)" -eq 1 ]
  done
}

@test "cairn-init re-run keeps every entry single across the full set" {
  require_bd
  make_tmp_repo

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]
  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]
  grep -qF '.cairn state files already gitignored' <<< "$output"

  local entry
  for entry in "${CAIRN_GITIGNORE_ENTRIES[@]}"; do
    [ "$(grep -cxF "$entry" .gitignore)" -eq 1 ]
  done
}

#-----------------------------------------------------------------------------
# Phase 28 (DJOUR-02): .cairn/journal/ is the ONE versioned thing under
# .cairn/, and it only merges correctly with `merge=union` in a TRACKED
# .gitattributes. A custom driver would not do: it needs merge.<name>.driver
# in .git/config, which git never clones, so a machine that skipped the setup
# falls back to the default merge and conflicts with markers, in silence
# (28-RESEARCH.md, E17).
#-----------------------------------------------------------------------------

@test "cairn-init sets merge=union on the journal partitions, and a re-run does not duplicate it" {
  require_bd
  make_tmp_repo

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh"
  [ "$status" -eq 0 ]
  [ -f .gitattributes ]
  [ "$(grep -cxF '.cairn/journal/*.jsonl merge=union' .gitattributes)" -eq 1 ]

  # The attribute actually resolves for a real segment path -- the line
  # existing is not the same as git applying it.
  run git check-attr merge -- .cairn/journal/host-0123456789ab-0001.jsonl
  [ "$status" -eq 0 ]
  grep -qF 'merge: union' <<<"$output"

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh"
  [ "$status" -eq 0 ]
  grep -qF 'journal partitions already set to merge=union' <<<"$output"
  [ "$(grep -cxF '.cairn/journal/*.jsonl merge=union' .gitattributes)" -eq 1 ]
}

@test "cairn-init leaves a pre-existing .gitattributes intact while adding the union line" {
  require_bd
  make_tmp_repo
  printf '*.png binary\n' > .gitattributes

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh"
  [ "$status" -eq 0 ]
  [ "$(grep -cxF '*.png binary' .gitattributes)" -eq 1 ]
  [ "$(grep -cxF '.cairn/journal/*.jsonl merge=union' .gitattributes)" -eq 1 ]
}

# Asserta que NEEDLE não aparece em FILE. (`! grep` não serve inline: o `!` do
# bash suprime o errexit, então a falha nunca falharia o teste.)
refute_in_file() {
  if grep -qF -- "$1" "$2"; then
    echo "achei '$1' em $2, e ele nao deveria estar la" >&2
    return 1
  fi
}

# ---------------------------------------------------------------------------
# A troca de plugin (fase 37, PLUG-03) — init para de recomendar um plugin
# externo, e a mão de saída aponta o namespace do cairn.
#
# Rodados contra o init pré-conversão: as duas primeiras asserções ficam
# vermelhas lá (o bloco `# 6. GSD presence` imprimia
# `claude plugin install gsd-core@cairngo` em dois de seus três ramos) e a
# terceira também (o heredoc NEXT mandava rodar `/gsd:new-project`).
# ---------------------------------------------------------------------------

@test "init nao recomenda mais instalar um plugin GSD externo" {
  refute_in_file "claude plugin install gsd-core" "$CAIRN_SCRIPTS_DIR/cairn-init.sh"
  refute_in_file "claude plugin list" "$CAIRN_SCRIPTS_DIR/cairn-init.sh"
}

@test "init nao instala mais a capability arquivada" {
  refute_in_file ".gsd/capabilities" "$CAIRN_SCRIPTS_DIR/cairn-init.sh"
  refute_in_file "capability install" "$CAIRN_SCRIPTS_DIR/cairn-init.sh"
}

@test "init entrega a mao para o namespace do cairn, nao para o do gsd" {
  local init="$CAIRN_SCRIPTS_DIR/cairn-init.sh"
  grep -qF "/cairn:new" "$init"
  grep -qF "/cairn:plan" "$init"
  grep -qF "/cairn:work" "$init"
  refute_in_file "/gsd:new-project" "$init"
  refute_in_file "/gsd:plan-phase" "$init"
  refute_in_file "/gsd:execute-phase" "$init"
}

@test "init confere o runtime vendorizado em vez de um plugin instalado" {
  # A asserção é sobre o FATO conferido, não sobre como o caminho é montado:
  # o manifesto que a fase 32 derivou é o que diz se o runtime está inteiro.
  grep -qF "MANIFEST.json" "$CAIRN_SCRIPTS_DIR/cairn-init.sh"
}
