#!/usr/bin/env bats
# cairn-board-invariance.bats — the board renders the same bytes it rendered
# before the model underneath it changed.
#
# Under test: the whole stdout render path of cairn-status.sh, compared
# byte for byte against references committed in tests/fixtures/board-render/
# and captured from cairn-status.py BEFORE phase 20 touched it, plus the
# machine contract in tests/fixtures/machine-contract/, captured before
# phase 22 split the non-TTY path (PIPE-01). "The existing tests still pass"
# is not proof that a render is unchanged — they cover what they already
# covered, and a change in the wrong place can pass all of them while moving
# a space, an order or a truncation. This file is the proof: the bytes, or
# nothing.
#
# The board references are regenerated by a human running
# `bash tests/fixtures/board-render/regenerate.sh` and READING the diff it
# prints. No test here may ever call it — a test that regenerates its own
# reference before comparing is a rubber stamp. The machine reference is not
# regenerable at all: see the comment above its test.
#
# Assertion style note (same as cairn-status.bats): a failing `[[ ]]` or
# `! cmd` mid-test does NOT fail a bats test on this bash, so every check
# lands on a plain `[ ]` over a run-captured `$status`.

load 'helpers'

STATUS_SH="$CAIRN_REPO_ROOT/cairn/scripts/cairn-status.sh"
BOARD_FIXTURES="$CAIRN_TESTS_DIR/fixtures/board-render"
# The SECOND reference set (Phase 22, PIPE-01), and the reason there are two.
# tests/fixtures/board-render/plain.txt already pins --plain — but it lives
# under regenerate.sh, which rewrites all seven of those files in one pass. An
# executor who changes the human render and regenerates rewrites plain.txt
# along with six others, inside a single commit, and the machine contract
# loses its guard without anyone having decided that. Nothing regenerates
# tests/fixtures/machine-contract/ alongside anything else; its capture.sh
# refuses to overwrite at all. The two files carry identical bytes today on
# purpose — that is redundancy with a reason, not an oversight.
MACHINE_FIXTURES="$CAIRN_TESTS_DIR/fixtures/machine-contract"

setup() {
  require_bd
  make_tmp_repo
  make_board_fixture "$PWD"
}

# Render with the given flags and diff against REFERENCE (a path), leaving
# diff's exit code in $status and its report in $output.
#
# EVERY direction goes through this one function: the seven render tests and
# the machine-bytes test assert 0 here, and the two liveness tests assert
# non-zero here. That is deliberate. If a liveness test carried a diff of its
# own, a comparison rigged to always agree would pass every positive test AND
# leave the liveness test green on its private, still-honest copy — the exact
# hole the liveness tests exist to close.
diff_against_reference() {
  local reference="$1"
  shift
  local actual="$BATS_TEST_TMPDIR/render-$(basename "$reference")"
  bash "$STATUS_SH" "$@" > "$actual"
  run diff -u "$reference" "$actual"
}

diff_render_against_reference() {
  local name="$1"
  shift
  diff_against_reference "$BOARD_FIXTURES/$name.txt" "$@" --color=never
}

# No --color=never here, and that is not an omission: the capture was taken
# with no flags at all (see machine-contract/capture.sh), so the comparison
# has to exercise the same command line. --color=never would not move a byte
# either way — render_plain() never consults Style — but a flag in one place
# and not the other is how two things that must agree start drifting.
diff_machine_against_reference() {
  diff_against_reference "$MACHINE_FIXTURES/nontty-pre-split.txt" --plain
}

# The reference direction: the bytes must match. Prints the diff on failure —
# an exit code alone says "different" and nothing about how.
assert_render_matches() {
  local name="$1"
  shift
  diff_render_against_reference "$name" "$@"
  if [ "$status" -ne 0 ]; then
    echo "render drifted from tests/fixtures/board-render/$name.txt" >&2
    printf '%s\n' "$output" >&2
  fi
  [ "$status" -eq 0 ]
}

# A reference that was emptied or truncated would happily match a render
# that broke and printed nothing. Size > 0, plus one or more anchors that
# only exist when that mode really rendered. Content anchors, not byte
# counts: a byte count needs editing on every legitimate change and rots
# into noise — and it would not even have caught the one case measured
# here, where maxrows.txt differs from w100.txt at an identical 1539 bytes.
assert_file_intact() {
  local file="$1"
  shift
  if [ ! -s "$file" ]; then
    echo "reference $(basename "$file") is missing or empty" >&2
    return 1
  fi
  local anchor
  for anchor in "$@"; do
    if ! grep -qF -- "$anchor" "$file"; then
      echo "reference $(basename "$file") lost its structural anchor:" \
        "'$anchor'" >&2
      return 1
    fi
  done
}

assert_reference_intact() {
  local name="$1"
  shift
  assert_file_intact "$BOARD_FIXTURES/$name.txt" "$@"
}

# ─── The reference renders ───────────────────────────────────────────────────

# One file per mode, because each one fails for a different reason: the
# list at three widths, the ASCII glyph set, the per-bucket overflow cut,
# and the two flag-selected formats.
#
# UPDATED 2026-08-05 (plan 21-02). w50 and w38 used to be the two width
# DEGRADES — different renderers, hence different failure modes. They are
# now the same renderer wrapping sooner, which sounds like it makes two of
# these files redundant and does not: w50 is the only file where a title
# wraps beside its id, and w38 is the only one where the body drops to its
# own line under NARROW_BODY. Three widths, three shapes.
#
# --json is deliberately NOT in this matrix. Phase 20 adds a key to it on
# purpose, so freezing its bytes here would freeze the phase against itself;
# its contract is "no existing key moves", proved by the model tests.

@test "the wide board renders the reference bytes" {
  assert_render_matches w100 --width 100
}

@test "the list wrapping beside the id renders the reference bytes" {
  assert_render_matches w50 --width 50
}

@test "the list with the body dropped below the id renders the reference bytes" {
  assert_render_matches w38 --width 38
}

@test "the ascii board renders the reference bytes" {
  assert_render_matches ascii100 --width 100 --ascii
}

# --max-rows 1 since Phase 21: the cap moved from a lane to a bucket, and at
# --max-rows 2 no bucket of this fixture overflows, so the reference would
# come out identical to w100.txt and stop guarding anything. Kept in step
# with tests/fixtures/board-render/regenerate.sh, which says the same.
@test "the bucket overflow cut renders the reference bytes" {
  assert_render_matches maxrows --width 100 --max-rows 1
}

@test "the machine format renders the reference bytes" {
  assert_render_matches plain --plain
}

# ─── The machine contract, on its own axis (Phase 22, PIPE-01) ───────────────

# `--plain` is what scripts consume, and PIPE-01 says it stays byte-for-byte
# what it was before Phase 22 split the non-TTY path off it. The reference is
# tests/fixtures/machine-contract/nontty-pre-split.txt: the bytes a FLAGLESS
# non-TTY run printed on 2026-08-06, captured before any code of that phase
# moved (md5 e98d3096656463236c2ed12a12be90e3, identical to plain.txt and to
# both `--plain` spellings — four command lines, one md5).
#
# ONE BYTE OF IT MOVED ON PURPOSE, 2026-08-13 (v1.7, CairnGo-fp7), and it is
# recorded here rather than absorbed: the `MILESTONE` row read `v1.0`, which
# is STATE.md's pointer at the ARCHIVED cycle, while this fixture's roadmap
# marks `v1.1 Surface` open. It now reads `v1.1`. New md5 for both files:
# a50fa27c5124bc42d433e7b98186c010. PIPE-01 froze the SHAPE of the row — tag,
# tab, position, and the set of rows — and the shape did not move; what it
# never froze was the row's right to answer with a cycle that closed. Every
# other byte of both references is the 2026-08-06 capture, untouched.
#
# If this test goes red, the machine contract moved. Regenerating the
# reference is NOT an option and capture.sh refuses to do it: the code path
# that produced those bytes no longer exists, so a fresh capture would record
# the human board and this test would go green having proved nothing. It is
# the change that has to come back, not the reference — and the one exception
# above is a decided, single-value edit with a bead id on it, not a capture.
@test "--plain still renders the pre-split machine bytes" {
  diff_machine_against_reference
  if [ "$status" -ne 0 ]; then
    echo "the --plain contract drifted from" \
      "tests/fixtures/machine-contract/nontty-pre-split.txt (PIPE-01)." \
      "Do NOT regenerate it — find what moved:" >&2
    printf '%s\n' "$output" >&2
  fi
  [ "$status" -eq 0 ]
}

@test "the three-line format renders the reference bytes" {
  assert_render_matches brief --brief
}

# ─── Proving the comparison is alive ─────────────────────────────────────────

@test "perturbing the fixture makes the comparison fail" {
  # Everything above would pass just as well against a comparison that can
  # never disagree — a diff of a file with itself, a normalization that
  # empties both sides, a trailing `|| true`. This is the test that kills
  # those: change one thing the board renders, and the comparison MUST go
  # red. `sed -i.bak` because BSD sed needs the suffix; the .bak lands in
  # the throwaway fixture, never in tests/fixtures/.
  sed -i.bak 's/Board fills the screen/Board fills the window/' \
    .planning/ROADMAP.md
  rm -f .planning/ROADMAP.md.bak
  diff_render_against_reference w100 --width 100
  # A sed that matched nothing would leave the render identical and fail
  # the check below — the perturbation cannot silently become a no-op.
  if ! printf '%s\n' "$output" | grep -qF "Board fills the window"; then
    echo "the diff does not mention the perturbation — it reports something" \
      "other than the change that was made:" >&2
    printf '%s\n' "$output" >&2
    return 1
  fi
  [ "$status" -ne 0 ]
}

# The same argument, for the machine reference. The perturbation has to reach
# the MACHINE format, and render_plain() prints `data["milestone"]` verbatim
# on its `MILESTONE\t...` row — so moving the cycle that row names makes the
# perturbation travel the whole path, from a file on disk to the compared
# bytes.
#
# IT USED TO MOVE STATE.md's `milestone: v1.0`, and that stopped working on
# 2026-08-13: CairnGo-fp7 took --plain off STATE.md, so editing that line is
# now a no-op and this liveness test would have failed for the right reason.
# The perturbation moves to the roadmap's own open-cycle line, which is where
# the answer comes from while a roadmap declares one. Same claim, same file,
# new address — and the guard below still refuses a perturbation that turned
# into a no-op.
@test "perturbing the fixture breaks the machine-bytes comparison" {
  sed -i.bak 's/^- 🚧 \*\*v1.1 Surface\*\*/- 🚧 **v9.9 Surface**/' \
    .planning/ROADMAP.md
  rm -f .planning/ROADMAP.md.bak
  diff_machine_against_reference
  # A sed that matched nothing would leave the render identical and fail the
  # check below — the perturbation cannot silently become a no-op.
  if ! printf '%s\n' "$output" | grep -qF "v9.9"; then
    echo "the diff does not mention the perturbation — it reports something" \
      "other than the change that was made:" >&2
    printf '%s\n' "$output" >&2
    return 1
  fi
  [ "$status" -ne 0 ]
}

@test "no reference file is empty or has lost its structure" {
  # w100, ascii100 and maxrows carry Phase 21 anchors: the counts line the
  # lane headers used to hold, the open cycle's group label, the loose group,
  # and one stage symbol.
  #
  # w50 and w38 anchored on `DOING (1)` and `BLOCKED  brd-005` until
  # 2026-08-05 — the lane header of the stacked degrade and the lane column
  # of the raw one. Plan 21-02 removed both renderers, so both anchors now
  # describe bytes that cannot be produced. They are replaced by anchors on
  # what makes each of those two files DIFFERENT from w100, which is the
  # only reason either file still earns a slot: in w50 a title wraps beside
  # its id, in w38 the body drops to its own line. Anchoring them on
  # something w100 also contains would let either file silently become a
  # copy of w100 and still pass.
  assert_reference_intact w100 "PENDING PHASES" "PURPOSE" \
    "ready 3 · doing 1 · blocked 1 · done 1" "v1.1 Surface" "No milestone" \
    "◔ brd-001  Read the roadmap into a phase model" \
    "blocked by brd-001"
  assert_reference_intact w50 "▶ next: " \
    "      ◔ brd-001  Read the roadmap into a phase" \
    "                 model"
  assert_reference_intact w38 "▶ next: " \
    "      ◔ brd-001" \
    "        Read the roadmap into a phase"
  assert_reference_intact ascii100 "PENDING PHASES" "PURPOSE" \
    "ready 3 | doing 1 | blocked 1 | done 1" "v1.1 Surface" "No milestone" \
    "o brd-001  Read the roadmap into a phase model" \
    "blocked by brd-001"
  assert_reference_intact maxrows "+1 more" "PENDING PHASES" "v1.1 Surface"
  # `v1.0` until 2026-08-13 (CairnGo-fp7): the row named STATE.md's pointer
  # at the archived cycle while the roadmap above it marked v1.1 open. The
  # anchor is the OPEN cycle now, on both files.
  assert_reference_intact plain "$(printf 'READY\tbrd-001')" \
    "$(printf 'MILESTONE\tv1.1')"
  assert_reference_intact brief "[cairn-status] phase 3/4" "▶ next: "
  # Same anchors as plain, on the second axis: an emptied capture would match
  # a --plain that broke and printed nothing just as happily.
  assert_file_intact "$MACHINE_FIXTURES/nontty-pre-split.txt" \
    "$(printf 'READY\tbrd-001')" "$(printf 'MILESTONE\tv1.1')"
}
