#!/usr/bin/env bats
# cairn-map.bats — exercises the map generator's CLI contract (cairn-map.py /
# the cairn-map.sh wrapper): NN-BEADS-MAP.md generation from bd state,
# marker-preserving regeneration, --check staleness, milestone inference, and
# the documented exit codes (0 ok, 2 usage/ambiguity, 3 stale, 4 phase dir
# not found, 5 bd unavailable).
#
# Assertion style note: a failing `[[ ]]` or `! cmd` mid-test does NOT fail a
# bats test on this bash, so substring checks use grep -qF and negative
# checks use refute_in_file.

load 'helpers'

# Assert NEEDLE does not appear in FILE. (`! grep` cannot be used inline:
# bash's `!` suppresses errexit, so its failure would never fail the test.)
refute_in_file() {
  if grep -qF -- "$1" "$2"; then
    echo "unexpectedly found '$1' in $2" >&2
    return 1
  fi
}

MAP_FILE=".planning/phases/01-auth/01-BEADS-MAP.md"

# Phase-1 fixture issues carrying the phase-1 + m-v1.0 label pair and a
# {"gsd": {...}} metadata stamp (dedup key: gsd.req + gsd.milestone).
# MAP_AUTH2 is closed via bd close; MAP_NOREQ carries no metadata.gsd.req and
# must land in the "issues without a requirement" gap list, not the table.
# Callers must require_bd and make_tmp_repo first.
make_map_fixture() {
  bd init -q --prefix map --non-interactive >/dev/null 2>&1
  MAP_AUTH1="$(bd create "Signup flow" -t task -l phase-1,m-v1.0 \
    --metadata '{"gsd":{"req":"AUTH-01","phase":1,"milestone":"v1.0"}}' --silent)"
  MAP_AUTH2="$(bd create "Login flow" -t task -l phase-1,m-v1.0 \
    --metadata '{"gsd":{"req":"AUTH-02","phase":1,"milestone":"v1.0"}}' --silent)"
  MAP_EXTRA="$(bd create "Password reset" -t task -l phase-1,m-v1.0 \
    --metadata '{"gsd":{"req":"AUTH-03","phase":1,"milestone":"v1.0"}}' --silent)"
  MAP_NOREQ="$(bd create "Stray chore" -t chore -l phase-1,m-v1.0 --silent)"
  bd close "$MAP_AUTH2" >/dev/null
}

@test "cairn-map creates the map: markers, rows incl. closed issue, gap lists" {
  require_bd
  make_tmp_repo
  make_gsd_fixture "$PWD"
  make_map_fixture

  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 1
  [ "$status" -eq 0 ]
  [ -f "$MAP_FILE" ]

  head -1 "$MAP_FILE" | grep -qF "# Phase 01 — beads map"
  grep -qF '<!-- cairn:generated:start -->' "$MAP_FILE"
  grep -qF '<!-- cairn:generated:end -->' "$MAP_FILE"
  grep -qF 'Generated by cairn-map' "$MAP_FILE"

  # All metadata-stamped issues appear as table rows — including the closed one.
  grep -qF "| AUTH-01 | $MAP_AUTH1 | open | Signup flow |" "$MAP_FILE"
  grep -qF "| AUTH-02 | $MAP_AUTH2 | closed | Login flow |" "$MAP_FILE"
  grep -qF "| AUTH-03 | $MAP_EXTRA | open | Password reset |" "$MAP_FILE"

  # The metadata-less issue lands in the issue gap list, not the table.
  grep -qF "## Gaps — issues without a requirement" "$MAP_FILE"
  grep -qF -- "- $MAP_NOREQ (open) Stray chore" "$MAP_FILE"
  refute_in_file "| $MAP_NOREQ |" "$MAP_FILE"

  # AUTH-01/AUTH-02 (the fixture ROADMAP requirements) are both mapped.
  grep -qF "None — every phase requirement is mapped to an issue." "$MAP_FILE"
}

@test "manual notes above the markers survive regeneration" {
  require_bd
  make_tmp_repo
  make_gsd_fixture "$PWD"
  make_map_fixture
  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 1
  [ "$status" -eq 0 ]

  # A human note above the generated block...
  printf 'Manual note: keep me\n%s\n' "$(cat "$MAP_FILE")" > "$MAP_FILE"

  # ...survives a regeneration that rewrites the marker block.
  bd close "$MAP_EXTRA" >/dev/null
  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 1
  [ "$status" -eq 0 ]
  grep -qF 'Manual note: keep me' "$MAP_FILE"
  grep -qF "| AUTH-03 | $MAP_EXTRA | closed | Password reset |" "$MAP_FILE"
  [ "$(grep -cF '<!-- cairn:generated:start -->' "$MAP_FILE")" -eq 1 ]
  [ "$(grep -cF '<!-- cairn:generated:end -->' "$MAP_FILE")" -eq 1 ]
}

@test "existing map without markers gets the block appended, content kept" {
  require_bd
  make_tmp_repo
  make_gsd_fixture "$PWD"
  make_map_fixture
  printf '# Hand-written map\n\nLegacy notes.\n' > "$MAP_FILE"

  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 1
  [ "$status" -eq 0 ]
  head -1 "$MAP_FILE" | grep -qF '# Hand-written map'
  grep -qF 'Legacy notes.' "$MAP_FILE"
  grep -qF '<!-- cairn:generated:start -->' "$MAP_FILE"
  grep -qF "| AUTH-01 | $MAP_AUTH1 | open | Signup flow |" "$MAP_FILE"
}

@test "--check: exit 0 when fresh, exit 3 with a diff after bd state changes" {
  require_bd
  make_tmp_repo
  make_gsd_fixture "$PWD"
  make_map_fixture
  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 1
  [ "$status" -eq 0 ]

  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 1 --check
  [ "$status" -eq 0 ]

  bd close "$MAP_AUTH1" >/dev/null
  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 1 --check
  [ "$status" -eq 3 ]
  grep -qF "stale" <<<"$output"
  grep -qF "AUTH-01" <<<"$output"

  # --check never writes: the file still shows the pre-close status.
  grep -qF "| AUTH-01 | $MAP_AUTH1 | open | Signup flow |" "$MAP_FILE"
}

@test "phase argument accepts '1' and '01' as the same phase" {
  require_bd
  make_tmp_repo
  make_gsd_fixture "$PWD"
  make_map_fixture

  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 01
  [ "$status" -eq 0 ]
  [ -f "$MAP_FILE" ]
  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 1 --check
  [ "$status" -eq 0 ]
}

@test "mixed m-* labels without --milestone exit 2; --milestone disambiguates" {
  require_bd
  make_tmp_repo
  make_gsd_fixture "$PWD"
  bd init -q --prefix map --non-interactive >/dev/null 2>&1
  local a b
  a="$(bd create "Signup flow" -t task -l phase-1,m-v1.0 \
    --metadata '{"gsd":{"req":"AUTH-01","phase":1,"milestone":"v1.0"}}' --silent)"
  b="$(bd create "Login flow v2" -t task -l phase-1,m-v2.0 \
    --metadata '{"gsd":{"req":"AUTH-02","phase":1,"milestone":"v2.0"}}' --silent)"

  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 1
  [ "$status" -eq 2 ]
  grep -qF -- "--milestone" <<<"$output"
  [ ! -f "$MAP_FILE" ]

  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 1 --milestone v1.0
  [ "$status" -eq 0 ]
  grep -qF "| AUTH-01 | $a | open |" "$MAP_FILE"
  refute_in_file "$b" "$MAP_FILE"
  # AUTH-02 belongs to phase 1 in the ROADMAP but has no v1.0 issue.
  grep -qF -- "- AUTH-02" "$MAP_FILE"
}

@test "legacy issues without m-* labels work; roadmap requirement gap listed" {
  require_bd
  make_tmp_repo
  make_gsd_fixture "$PWD"
  bd init -q --prefix map --non-interactive >/dev/null 2>&1
  local c map
  c="$(bd create "Rate limiter spike" -t task -l phase-2 \
    --metadata '{"gsd":{"req":"API-99","phase":2,"milestone":"v1.0"}}' --silent)"

  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 2
  [ "$status" -eq 0 ]
  map=".planning/phases/02-api/02-BEADS-MAP.md"
  grep -qF "| API-99 | $c | open | Rate limiter spike |" "$map"
  grep -qF "## Gaps — requirements without an issue" "$map"
  grep -qF -- "- API-01" "$map"
}

@test "--json prints a machine summary with rows, gaps, and changed" {
  require_bd
  make_tmp_repo
  make_gsd_fixture "$PWD"
  make_map_fixture

  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 1 --json
  [ "$status" -eq 0 ]
  assert_json_eq "$output" '.phase' '1'
  assert_json_eq "$output" '.milestone' 'v1.0'
  assert_json_eq "$output" '.rows' '3'
  assert_json_eq "$output" '.gaps.issues_without_requirement' '1'
  assert_json_eq "$output" '.gaps.requirements_without_issue' '0'
  assert_json_eq "$output" '.changed' 'true'
  jq -r '.file' <<<"$output" | grep -q '/01-BEADS-MAP\.md$'

  # Second run regenerates identical marker content.
  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 1 --json
  [ "$status" -eq 0 ]
  assert_json_eq "$output" '.changed' 'false'
}

@test "missing phase directory exits 4" {
  make_tmp_repo
  make_gsd_fixture "$PWD"

  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 7
  [ "$status" -eq 4 ]
}

@test "usage errors exit 2" {
  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh"
  [ "$status" -eq 2 ]
  run bash "$CAIRN_SCRIPTS_DIR/cairn-map.sh" not-a-number
  [ "$status" -eq 2 ]
}

@test "bd missing from PATH exits 5" {
  make_tmp_repo
  make_gsd_fixture "$PWD"
  local stub="$BATS_TEST_TMPDIR/nobd-bin"
  mkdir -p "$stub"
  # Link the real interpreter (not a version-manager shim needing PATH).
  ln -s "$(python3 -c 'import sys; print(sys.executable)')" "$stub/python3"
  ln -s "$(command -v bash)" "$stub/bash"
  ln -s "$(command -v dirname)" "$stub/dirname"

  run env PATH="$stub" "$stub/bash" "$CAIRN_SCRIPTS_DIR/cairn-map.sh" 1
  [ "$status" -eq 5 ]
}
