#!/usr/bin/env bats
# cairn-init.bats — exercises cairn/scripts/cairn-init.sh against throwaway
# repos: git + bd bootstrap, the .gitignore entries promised by docs/sync.md §4,
# and idempotent re-runs (no duplicate lines).

load 'helpers'

# Every entry cairn-init must gitignore (docs/sync.md §4). The first three are
# the pre-1.4 set; the rest were generated by v1.4 code with no ignore rule.
CAIRN_GITIGNORE_ENTRIES=(
  '.cairn/id-map.json'
  '.cairn/state.json'
  '.cairn/conflicts.json'
  '.cairn/journal.jsonl*'
  '.cairn/reconcile-evidence.json'
  '.cairn/hook.log'
  '.cairn/migrate-plan.json'
  '.cairn/migrate-state.json'
  '.cairn/plugin-root'
)

# The pre-1.4 .gitignore, verbatim — the state of anyone upgrading from 1.4.x.
CAIRN_LEGACY_ENTRIES=(
  '.cairn/id-map.json'
  '.cairn/state.json'
  '.cairn/conflicts.json'
)

# Create one file per generated path under .cairn/, in the cwd repo. Includes
# the two siblings cairn-journal.py writes next to the journal (a compaction
# temp file and the compaction lock) — an exact-name ignore would miss both.
make_cairn_generated_files() {
  mkdir -p .cairn
  local f
  for f in id-map.json state.json conflicts.json journal.jsonl \
           journal.jsonl.tmp-abc123 journal.jsonl.compact.lock \
           reconcile-evidence.json hook.log migrate-plan.json \
           migrate-state.json plugin-root; do
    printf 'generated\n' > ".cairn/$f"
  done
}

# Create the two .cairn/ files that are meant to be COMMITTED: the sync backend
# config and the optional context-budget tuning. Both configure the whole team.
make_cairn_committable_files() {
  mkdir -p .cairn
  printf '{"backends":{}}\n' > .cairn/sync.json
  printf '{"budget":{}}\n' > .cairn/context.json
}

# Print every `git status` untracked path under .cairn/, one per line. Uses
# -uall so git lists files individually instead of collapsing a fully-untracked
# .cairn/ into a single `?? .cairn/` line.
cairn_untracked() {
  git status --porcelain -uall | sed -n 's/^?? //p' | grep '^\.cairn/'
}

@test "cairn-init bootstraps git + bd and gitignores the .cairn state files" {
  require_bd
  make_tmp_repo

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]

  [ -d .git ]
  [ -d .beads ]
  local entry
  for entry in "${CAIRN_GITIGNORE_ENTRIES[@]}"; do
    grep -qxF "$entry" .gitignore
  done
}

@test "cairn-init re-run is idempotent — no duplicate .gitignore entries" {
  require_bd
  make_tmp_repo

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]
  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]
  grep -qF '.cairn state files already gitignored' <<< "$output"

  local entry
  for entry in "${CAIRN_GITIGNORE_ENTRIES[@]}"; do
    [ "$(grep -cxF "$entry" .gitignore)" -eq 1 ]
  done
}

@test "cairn-init completes a legacy .gitignore that only has the retired .beacon-sent marker" {
  require_bd
  make_tmp_repo
  printf '.cairn/.beacon-sent\n' > .gitignore

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]

  # The legacy entry is left alone (still single); every missing entry is
  # appended once each. cairn-init no longer writes .beacon-sent itself.
  [ "$(grep -cxF '.cairn/.beacon-sent' .gitignore)" -eq 1 ]
  local entry
  for entry in "${CAIRN_GITIGNORE_ENTRIES[@]}"; do
    [ "$(grep -cxF "$entry" .gitignore)" -eq 1 ]
  done
}

@test "after cairn-init no generated .cairn file shows up as untracked" {
  require_bd
  make_tmp_repo
  make_cairn_generated_files

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]

  # Phase 18's symptom: a prepared worktree that stays `?? .cairn/` forever,
  # so cleanup never considers it removable. grep exits 1 on no match, so
  # status 1 IS the passing case; any leftover is echoed for diagnosis.
  run cairn_untracked
  if [ "$status" -eq 0 ]; then
    echo "still untracked under .cairn/:" >&2
    echo "$output" >&2
  fi
  [ "$status" -eq 1 ]
}

@test "cairn-init leaves the committable .cairn config files visible to git" {
  require_bd
  make_tmp_repo
  make_cairn_generated_files
  make_cairn_committable_files

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]

  # sync.json (docs/sync.md §4) and context.json configure the whole team, so
  # git must still see them. This is what forbids the one-line shortcuts —
  # ignoring `.cairn/` wholesale, or a `.cairn/*.json` wildcard — both of which
  # would hide files a team is meant to share.
  run git status --porcelain -uall
  [ "$status" -eq 0 ]
  grep -qF '?? .cairn/sync.json' <<< "$output"
  grep -qF '?? .cairn/context.json' <<< "$output"
}

@test "cairn-init upgrades a pre-1.4 .gitignore without duplicating its entries" {
  require_bd
  make_tmp_repo
  printf '%s\n' "${CAIRN_LEGACY_ENTRIES[@]}" > .gitignore

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]

  # REL-04's actual scenario: this is what "re-run /cairn:init" has to do on
  # the machine of someone who installed before v1.4. Every entry ends up
  # present exactly once — the ones that were already there included.
  local entry
  for entry in "${CAIRN_GITIGNORE_ENTRIES[@]}"; do
    [ "$(grep -cxF "$entry" .gitignore)" -eq 1 ]
  done
}

@test "cairn-init re-run keeps every entry single across the full set" {
  require_bd
  make_tmp_repo

  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]
  run bash "$CAIRN_SCRIPTS_DIR/cairn-init.sh" "$PWD"
  [ "$status" -eq 0 ]
  grep -qF '.cairn state files already gitignored' <<< "$output"

  local entry
  for entry in "${CAIRN_GITIGNORE_ENTRIES[@]}"; do
    [ "$(grep -cxF "$entry" .gitignore)" -eq 1 ]
  done
}
