#!/usr/bin/env bats
# cairn-board-invariance.bats — the board renders the same bytes it rendered
# before the model underneath it changed.
#
# Under test: the whole stdout render path of cairn-status.sh, compared
# byte for byte against references committed in tests/fixtures/board-render/
# and captured from cairn-status.py BEFORE phase 20 touched it. "The existing
# tests still pass" is not proof that a render is unchanged — they cover what
# they already covered, and a change in the wrong place can pass all of them
# while moving a space, an order or a truncation. This file is the proof:
# the bytes, or nothing.
#
# The references are regenerated by a human running
# `bash tests/fixtures/board-render/regenerate.sh` and READING the diff it
# prints. No test here may ever call it — a test that regenerates its own
# reference before comparing is a rubber stamp.
#
# Assertion style note (same as cairn-status.bats): a failing `[[ ]]` or
# `! cmd` mid-test does NOT fail a bats test on this bash, so every check
# lands on a plain `[ ]` over a run-captured `$status`.

load 'helpers'

STATUS_SH="$CAIRN_REPO_ROOT/cairn/scripts/cairn-status.sh"
BOARD_FIXTURES="$CAIRN_TESTS_DIR/fixtures/board-render"

setup() {
  require_bd
  make_tmp_repo
  make_board_fixture "$PWD"
}

# Render the fixture with the given flags and diff it against the committed
# reference NAME, leaving diff's exit code in $status and its report in
# $output.
#
# BOTH directions go through this one function: the seven render tests
# assert 0 here, and the liveness test asserts non-zero here. That is
# deliberate. If the liveness test carried a diff of its own, a comparison
# rigged to always agree would pass all seven AND leave the liveness test
# green on its private, still-honest copy — the exact hole the liveness
# test exists to close.
diff_render_against_reference() {
  local name="$1"
  shift
  local actual="$BATS_TEST_TMPDIR/render-$name.txt"
  bash "$STATUS_SH" "$@" --color=never > "$actual"
  run diff -u "$BOARD_FIXTURES/$name.txt" "$actual"
}

# The reference direction: the bytes must match. Prints the diff on failure —
# an exit code alone says "different" and nothing about how.
assert_render_matches() {
  local name="$1"
  shift
  diff_render_against_reference "$name" "$@"
  if [ "$status" -ne 0 ]; then
    echo "render drifted from tests/fixtures/board-render/$name.txt" >&2
    printf '%s\n' "$output" >&2
  fi
  [ "$status" -eq 0 ]
}

# A reference that was emptied or truncated would happily match a render
# that broke and printed nothing. Size > 0, plus one or more anchors that
# only exist when that mode really rendered. Content anchors, not byte
# counts: a byte count needs editing on every legitimate change and rots
# into noise — and it would not even have caught the one case measured
# here, where maxrows.txt differs from w100.txt at an identical 1539 bytes.
assert_reference_intact() {
  local name="$1"
  shift
  local file="$BOARD_FIXTURES/$name.txt"
  if [ ! -s "$file" ]; then
    echo "reference $name.txt is missing or empty" >&2
    return 1
  fi
  local anchor
  for anchor in "$@"; do
    if ! grep -qF -- "$anchor" "$file"; then
      echo "reference $name.txt lost its structural anchor: '$anchor'" >&2
      return 1
    fi
  done
}

# ─── The reference renders ───────────────────────────────────────────────────

# One file per mode, because each one fails for a different reason: the
# column board, the two width degrades, the ASCII glyph set, the per-lane
# overflow cut, and the two flag-selected formats.
#
# --json is deliberately NOT in this matrix. Phase 20 adds a key to it on
# purpose, so freezing its bytes here would freeze the phase against itself;
# its contract is "no existing key moves", proved by the model tests.

@test "the wide board renders the reference bytes" {
  assert_render_matches w100 --width 100
}

@test "the stacked degrade renders the reference bytes" {
  assert_render_matches w50 --width 50
}

@test "the raw degrade renders the reference bytes" {
  assert_render_matches w38 --width 38
}

@test "the ascii board renders the reference bytes" {
  assert_render_matches ascii100 --width 100 --ascii
}

# --max-rows 1 since Phase 21: the cap moved from a lane to a bucket, and at
# --max-rows 2 no bucket of this fixture overflows, so the reference would
# come out identical to w100.txt and stop guarding anything. Kept in step
# with tests/fixtures/board-render/regenerate.sh, which says the same.
@test "the bucket overflow cut renders the reference bytes" {
  assert_render_matches maxrows --width 100 --max-rows 1
}

@test "the machine format renders the reference bytes" {
  assert_render_matches plain --plain
}

@test "the three-line format renders the reference bytes" {
  assert_render_matches brief --brief
}

# ─── Proving the comparison is alive ─────────────────────────────────────────

@test "perturbing the fixture makes the comparison fail" {
  # Everything above would pass just as well against a comparison that can
  # never disagree — a diff of a file with itself, a normalization that
  # empties both sides, a trailing `|| true`. This is the test that kills
  # those: change one thing the board renders, and the comparison MUST go
  # red. `sed -i.bak` because BSD sed needs the suffix; the .bak lands in
  # the throwaway fixture, never in tests/fixtures/.
  sed -i.bak 's/Board fills the screen/Board fills the window/' \
    .planning/ROADMAP.md
  rm -f .planning/ROADMAP.md.bak
  diff_render_against_reference w100 --width 100
  # A sed that matched nothing would leave the render identical and fail
  # the check below — the perturbation cannot silently become a no-op.
  if ! printf '%s\n' "$output" | grep -qF "Board fills the window"; then
    echo "the diff does not mention the perturbation — it reports something" \
      "other than the change that was made:" >&2
    printf '%s\n' "$output" >&2
    return 1
  fi
  [ "$status" -ne 0 ]
}

@test "no reference file is empty or has lost its structure" {
  # w100, ascii100 and maxrows carry Phase 21 anchors: the counts line the
  # lane headers used to hold, the open cycle's group label, the loose group,
  # and one stage symbol. w50 and w38 still describe the stacked and raw
  # degrades, which plan 21-01 leaves standing.
  assert_reference_intact w100 "PENDING PHASES" "PURPOSE" \
    "ready 3 · doing 1 · blocked 1 · done 1" "v1.1 Surface" "No milestone" \
    "◔ brd-001  Read the roadmap into a phase model" \
    "blocked by brd-001"
  assert_reference_intact w50 "DOING (1)" "▶ next: "
  assert_reference_intact w38 "BLOCKED  brd-005" "▶ next: "
  assert_reference_intact ascii100 "PENDING PHASES" "PURPOSE" \
    "ready 3 | doing 1 | blocked 1 | done 1" "v1.1 Surface" "No milestone" \
    "o brd-001  Read the roadmap into a phase model" \
    "blocked by brd-001"
  assert_reference_intact maxrows "+1 more" "PENDING PHASES" "v1.1 Surface"
  assert_reference_intact plain "$(printf 'READY\tbrd-001')" \
    "$(printf 'MILESTONE\tv1.0')"
  assert_reference_intact brief "[cairn-status] phase 3/4" "▶ next: "
}
